retrieval_model: /data/CS470_HnC/retrieval_model/wandb/run-20221115_141017-qn8zgvm8/files/00000000.ckpt
ckpt_path: /data/CS470_HnC/cookgan/wandb/run-20221117_162130-2ezrqode/files/000000.ckpt
ckpt_dir: /data/CS470_HnC/cookgan/wandb/run-20221117_162130-2ezrqode/files/
batch_size: 64
n_sample: 5000
inception: inception_Recipe1M_salad.pkl
device: cuda